[package]
name = "aleo-std-storage"
version = "0.1.7"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Convenience methods for accessing resources in Aleo storage"
license = "GPL-3.0"
edition = "2018"

[dependencies.dirs]
version = "4.0"
